invoice/urls.py
from django.urls import path, re_path
from . import views
from trackingCard import views as trackingCardViews
from django.conf import settings
from django.conf.urls.static import static


app_name = 'invoice'

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    #path('home/', views.home, name='home'),
    path('home/', trackingCardViews.createWorkOrder, name='home'),
    path('createInvoice/', views.createInvoice, name='createInvoice'),
    path('createInvoice2/', views.createInvoice2, name='createInvoice2'),
    path("invoiceHistory/", views.invoiceHistory, name="invoiceHistory"),
    path("addProductsClients/", views.addProductsClients, name="addProductsClients"),
    path('addItems/<int:invoice_id>/', views.addItems, name='addItems'),
    path('editInvoiceItem/<int:invoice_pk>/<int:id>/', views.editInvoiceItem, name="editInvoiceItem"),
    path("pdf/<int:invoice_id>", views.pdf, name="pdf"),
    path("createClient/", views.createClient, name="createClient"),
    path("createClientContact/", views.createClientContact, name="createClientContact"),
    path('products/createProduct/', views.createProduct, name="createProduct"),
    path('products/createProductType/', views.createProductType, name="createProductType"),
    
    
    #path('register/', views.registerPage, name="registerPage"),
    path('login/', views.loginPage, name="loginPage"),
    path('logout/', views.logoutUser, name="logout"),
    path('check-login/', views.check_login, name='check_login'),
    
    
    path('trackingCardsPDF/<int:workOrder_id>', trackingCardViews.pdfTracker, name='pdfTracker'),
    path('customerTrackingPDF/<int:workOrder_id>', trackingCardViews.pdfCustomerTracking, name='pdfCustomerTracking'),
    path('shopWorkDashboard/', trackingCardViews.shopWorkDashboard, name='shopWorkDashboard'),
    path('createWorkOrder/', trackingCardViews.createWorkOrder, name='createWorkOrder'),
    path('addItemsWorkOrder/<int:workOrder_id>/', trackingCardViews.addItemsWorkOrder, name='addItemsWorkOrder'),
    path('customWorkOrderItem/<int:workOrder_id>/', trackingCardViews.customWorkOrderItem, name="customWorkOrderItem"),
    path('editWorkOrderItem/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItem, name="editWorkOrderItem"),
    path("workOrderHistory/", trackingCardViews.workOrderHistory, name="workOrderHistory"),
    path("deleteWorkOrderItem/<int:workOrder_id>/<int:id>/", trackingCardViews.deleteWorkOrderItem, name="deleteWorkOrderItem"),
    path("workOrderView/<int:workOrder>/", trackingCardViews.workOrderView, name="workOrderView"),
    path('signature_page/<int:workOrder_id>/', trackingCardViews.signature_page, name='signature_page'),
    path('signature_page/shopWorkDashboard', trackingCardViews.shopWorkDashboard, name='shopWorkDashboard'),



    path('invoice/api/createInvoice/', views.createInvoiceAPI, name='createInvoiceAPI'),
    path('invoice/api/invoiceAll/', views.invoiceAllAPI, name="invoiceAllAPI"),
    path('invoice/api/itemInvoice/<int:invoice_pk>/', views.itemInvoiceAPI, name="itemInvoiceAPI"),
    path('invoice/api/productsID/<int:id>/', views.productsIDAPI, name="productsIDAPI"),
    path('invoice/api/clientAll/', views.clientsAllAPI, name="clientAllAPI"),
    path('invoice/api/newestProduct/<int:invoice_pk>/', views.newestProductAPI, name="newestProductAPI"),
    path('invoice/api/editInvoiceItem/<int:invoice_pk>/<int:id>/', views.editInvoiceItemAPI, name="editInvoiceItemAPI"),
    path('invoice/api/deleteInvoiceItem/<int:id>/', views.deleteInvoiceItemAPI, name="deleteInvoiceItemAPI"),
    path('invoice/get_invoice_item_count/<int:invoice_id>/', views.get_invoice_item_count, name='get_invoice_item_count'),
    path('invoice/api/invoiceItemNumber/<int:id>/', views.itemInvoiceNumberAPI, name='invoiceItemNumberAPI'),

    path('workOrder/api/createWorkOrder/', trackingCardViews.createWorkOrderAPI, name='createWorkOrderAPI'),
    path('workOrder/api/itemWorkOrder/<int:workOrder_id>/', trackingCardViews.itemWorkOrderAPI, name="itemWorkOrderAPI"),
    path('workOrder/getWorkOrderItemCount/<int:workOrder_id>/', trackingCardViews.getWorkOrderItemCount, name='getWorkOrderItemCount'),
    path('workOrder/api/workOrderItemNumber/<int:id>/', trackingCardViews.itemWorkOrderNumberAPI, name='itemworkOrderNumberAPI'),
    path('workOrder/api/itemWorkOrder/<int:workOrder_id>/', trackingCardViews.itemWorkOrderAPI, name="itemWorkOrderAPI"),
    path('editWorkOrderItemAPI/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItemAPI, name="editWorkOrderItemAPI"),
    path('workOrder/api/deleteWorkOrderItem/', trackingCardViews.deleteWorkOrderItemAPI, name="deleteWorkOrderItemAPI"),
    path('workOrder/api/newestProduct/<int:workOrder_id>/', trackingCardViews.newestWorkOrderProductAPI, name="newestWorkOrderProductAPI"),
    path('workOrder/api/workOrderItemOther/<int:id>/', trackingCardViews.workOrderItemOther, name="workOrderItemOther"),
    path('workOrder/api/editWorkOrderItem/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItemAPI, name="editWorkOrderItemAPI"),
    path('workOrder/api/addColor/<int:workOrder_id>/', trackingCardViews.workOrderColorAPI, name="workOrderColorAPI"),
    path('workOrder/api/workOrderView/', trackingCardViews.workOrderViewAPI, name="workOrderViewAPI"),
    path('workOrder/api/workOrderEnrichment/', trackingCardViews.workOrderEnrichment, name="workOrderEnrichment"),
    path('workOrder/api/signature/', trackingCardViews.signatureAPI, name="signatureAPI"),
    path('workOrder/api/addItemTestAPI/', trackingCardViews.addItemTestAPI, name="addItemTestAPI"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoiceme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoice.urls")),
]

invoice/views.py
from django.shortcuts import render, redirect
from .models import *
from .filters import *
from .forms import *
from .serializers import *
from .urls import *
import requests
import json
from django.http import HttpResponse, JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from django.core.paginator import Paginator, Page
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import *
from datetime import date
import io
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter


'''
@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            
            return redirect('invoice:loginPage')

    context = {'form': form}

    return render(request, 'accounts/register.html', context)
'''
@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('invoice:home')
        else:
            messages.info(request, 'Username Or Password is incorrect')
    
    context = {}

    return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('invoice:loginPage')


def landingPage(request):
    context= {}
    return render(request, 'index/landing.html', context)



def check_login(request):
    if request.user.is_authenticated:
        return redirect('invoice:home')
    else:
        # Handle the case where the user is not authenticated.
        return redirect('invoice:loginPage')


@login_required(login_url='invoice:loginPage')
def home(request):
    context= {}
    return render(request, 'tracking/home.html', context)

@api_view(['POST'])
def createInvoiceAPI(request):
    if request.method == 'POST':
        serializer = invoiceSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET'])
def invoiceAllAPI(request):
    #http://127.0.0.1:8000/invoice/api/invoiceAll/
    if request.method == "GET":
        invoice = Invoice.objects.all()
        serializer = invoiceSerializer(invoice,many=True)
        return JsonResponse(serializer.data, safe=False)

@api_view(['GET'])
def clientsAllAPI(request):
    #http://127.0.0.1:8000/invoice/api/clientAll/
    if request.method == "GET":
        client = Client.objects.all()
        serializer = clientSerializer(client,many=True)
        return JsonResponse(serializer.data, safe=False)
    
@api_view(['PUT'])
def itemInvoiceNumberAPI(request, id):
    try:
        item = InvoiceItem.objects.get(pk=id)  # Use get() to retrieve a single instance
    except InvoiceItem.DoesNotExist:
        return JsonResponse({'error': 'Item not found'}, status=404)
    
    if request.method == "PUT":
        serializer = invoiceItemNumberSerializer(item, data=request.data)  # Pass request data to the serializer
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
    
    return JsonResponse({'error': 'Invalid request method'}, status=400)


@api_view(['GET','POST'])  
def itemInvoiceAPI(request, invoice_pk):
    if request.method == "GET":
        try:
            items = InvoiceItem.objects.filter(invoice=invoice_pk)
            serializer = invoiceItemSerializer(items, many=True)
            return Response(serializer.data)
        except InvoiceItem.DoesNotExist:
            return Response([], status=status.HTTP_200_OK)  # Return an empty list if no items are found for the given invoice
    elif request.method == "POST":
        serializer = invoiceItemSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

    # Handle other HTTP methods
    return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)


@api_view(['GET'])
def productsIDAPI(request, id):
    if request.method == "GET":
        product= Product.objects.get(pk=id)
        serializer = productSerializer(product)
        return JsonResponse(serializer.data, safe=False)
    return

@api_view(['GET'])
def newestProductAPI(request, invoice_pk):
    if request.method == "GET":
        try:
            # Get the specific invoice
            invoice = Invoice.objects.get(invoice_num=invoice_pk)

            # Get the most recent item for the given invoice
            item = InvoiceItem.objects.filter(invoice=invoice).order_by('-created_at')[:1]

            serializer = invoiceItemSerializer(item, many=True)
            return JsonResponse(serializer.data, safe=False)
        except Invoice.DoesNotExist:
            # Handle the case where the specified invoice does not exist
            return JsonResponse({'error': 'Invoice not found'}, status=404)
        
@api_view(['PUT'])
def editInvoiceItemAPI(request, invoice_pk, id):
    try:
        # Try to get the InvoiceItem with the specified ID
        invoice_item = InvoiceItem.objects.get(pk=id)
    except InvoiceItem.DoesNotExist:
        # If the InvoiceItem does not exist, return a 404 Not Found response
        return Response({'detail': 'InvoiceItem not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        # Assuming you have a serializer for your InvoiceItem model
        serializer = invoiceItemSerializer(invoice_item, data=request.data)
        
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    return Response({'detail': 'Invalid request method'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['DELETE'])
def deleteInvoiceItemAPI(request, id):
    try:
        # Try to get the InvoiceItem with the specified ID
        invoice_item = InvoiceItem.objects.get(pk=id)
    except InvoiceItem.DoesNotExist:
        # If the InvoiceItem does not exist, return a 404 Not Found response
        return Response({'detail': 'InvoiceItem not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == "DELETE":
        # If the request method is DELETE, delete the InvoiceItem
        invoice_item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
@api_view(['GET']) 
def get_invoice_item_count(request, invoice_id):
    count = InvoiceItem.objects.filter(invoice_id=invoice_id).count()
    data = {'count': count}
    return JsonResponse(data)


# this is probably how i should do it
@login_required(login_url='invoice:loginPage')
def createInvoice2(request):
    clients2 = Client.objects.all()
    clientFilter2 = ClientFilter(request.GET, queryset=clients2)
    clients2 = clientFilter2.qs

    form2 = InvoiceForm2(request.POST) 

    if request.method == 'POST':
        
        if form2.is_valid():
            # Save the form to create an invoice
            invoice=form2.save()
            # Redirect to the next step (e.g., 'addItems') with the invoice ID
            return redirect('invoice:addItems', invoice_id=invoice.id)

    context = {
        'form2': form2,
        'clients': clients2,
        'clientFilter': clientFilter2
    }

    return render(request, 'invoice/createInvoice.html', context)


@login_required(login_url='invoice:loginPage')
def createInvoice(request):
    clients = Client.objects.all()
    clientFilter = ClientFilter(request.GET, queryset=clients)
    clients = clientFilter.qs
    if request.method == 'POST':
        form = InvoiceForm(request.POST)
        if form.is_valid():
            client_id = form.cleaned_data['client'].id 

            today = date.today()

            # Format the date as a string in 'YYYY-MM-DD' format
            invoice_date_str = today.strftime('%Y-%m-%d')


            # Create the API payload using the serialized client data
            api_payload = {
                "client": client_id,
                "invoice_date": invoice_date_str,
                "items": [],
                "status": "Draft"
            }

            # Define the API endpoint URL where you want to send the POST request
            api_url = f'{settings.SITE_URL}/invoice/api/createInvoice/'
            print(api_url)
            print("test")
            print(api_payload)

            try:
                response = requests.post(api_url, json=api_payload)


                if response.status_code == 201:  # Replace with the appropriate status code
                    response_data = json.loads(response.text)
                    invoice_id = response_data.get('invoice_num')
                    print(response_data)
                    print(invoice_id)
                    # Invoice created successfully
                    return redirect('invoice:addItems', invoice_id)
                else:
                    # Handle API call errors, e.g., show an error message
                    return render(request, 'invoice/createInvoice.html', {'form': form, 'error_message': 'Failed to create invoice'})

            except requests.exceptions.RequestException as e:

invoice/templates/invoice/addItems.html
{% extends "base/base.html" %}
{% load static %}


{% block content %}
<div class="row" style="margin: 15px 0px 0px 30px;">
    <div class="col-md-4">
        <div class="d-grid gap-2 col-6 mx-auto">
    <a href="{% url 'invoice:pdf' invoice %}" target="_blank" class="btn btn-primary">Preview PDF</a>
        </div>
    </div>
    <div class="col-md-8">
        <h1>Add Items to Invoice</h1>
    </div>
    
</div>


<div class="row" style="min-height: 600px;">
    <div class="col-md-5 card card-body">
        <table class="table" id="item-table">
            <tr>
                <th>Number</th>
                <th>Product Name</th>
                <th>Unit Price</th>
                <th>Quantity</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </table>
    </div>
    

    <div class="col-md-7 ">
        <div>
        
            <div class="card card-body" style="margin-bottom: 15px;">
                <form method="get">
                    {{myFilter.form.as_table}}
                    <button class="btn btn-primary">Search</button>
                    <a class="btn btn-warning" href="{% url 'invoice:addItems' invoice%}">Reset</a>
                </form>
            </div>

            <div class="card card-body" style="min-height: 500px;">
                <form method="post" id="invoiceForm">
                    {% csrf_token %}
                    <table class="table">
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th>Product Type</th>
                            <th>Quantity</th>
                            <th>Add Item</th>
                        </tr>
                        {% for i in products %}
                            <tr>
                                <td>{{ i.name }}</td>
                                <td>{{ i.description }}</td>
                                <td>{{ i.price }}</td>
                                <td>{{ i.product_type }}</td>
                                <td>
                                    <input type="number" class="quantity-input" name="quantity" min="1">
                                    <input type="hidden" name="product" value="{{ i.pk }}">
                                    <input type="hidden" name="invoice" value="{{ invoice_pk }}">
                                </td>
                                <td>
                                    <button type="button" class="submit-button">Add Item</button>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </form>
            </div>
        </div>
        <div class="pagination text-center" >
            <span class="step-links">
                {% if products.has_next %}
                    <a href="?page={{ products.paginator.num_pages }}">last</a>
                    <a href="?page={{ products.next_page_number }}">next</a>
                {% endif %}
            
                <span class="current-page">
                    Page {{ products.number }} of {{ products.paginator.num_pages }}.
                </span>
            
                {% if products.has_previous %}
                    <a href="?page={{ products.previous_page_number }}">previous</a>
                    <a href="?page=1">first</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.5.1.js" ></script>
<script>
let invoice_pk = '{{ invoice }}';
let site_url = '{{ site_url }}';
let apiUrl = "{% url 'invoice:itemInvoiceAPI' invoice_pk %}";
let crsfToken = '{% csrf_token %}';
</script>

<script src="{% static 'js/addItems.js' %}"></script>


{% endblock content %}

invoice/templates/invoice/addProductsClients.html
{% extends "base/base.html" %}

{% block content %}

<h1 style="text-align: center;">Add Instruments and Clients</h1>

<div class="container">
    <div class="row" >
        <div class="col-md-4 card card-body">
            <a href="{% url 'invoice:createProductType' %}" target="_blank" class="btn btn-primary">Add Instrument Type</a>
        </div>
        <div class="col-md-4 card card-body">
            <a href="{% url 'invoice:createProduct' %}" target="_blank" class="btn btn-primary">Add Instrument</a>
        </div>
        
        
    </div>
    <div class="row">
        <div class="col-md-4 card card-body">
            <a href="{% url 'invoice:createClient' %}" target="_blank" class="btn btn-primary">Add Client</a>
        </div>
        <div class="col-md-4 card card-body">
            <a href="{% url 'invoice:createClientContact' %}" target="_blank" class="btn btn-primary">Add Client Contact</a>
        </div>
    
    </div>
</div>







{% endblock content %}

invoice/templates/invoice/createClient.html
{% extends "base/base.html" %}

{% block content %}
<div style="text-align: center;">
    <h1>Add Account</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ client_form }}
        <button type="submit">Submit</button>
    </form>

    {% endblock content %}

</div>

invoice/templates/invoice/createClientContact.html
{% extends "base/base.html" %}

{% block content %}

<div style="text-align: center;">
    <h1>Add Account Contact</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ client_form }}
        <button type="submit">Submit</button>
    </form>

    {% endblock content %}

</div>

invoice/templates/invoice/createInvoice.html
{% extends "base/base.html" %}

{% block content %}
<h1>Generate your invoice</h1>
<div class="row">
    <div class="col-2"></div>
    <div class="col-md-8">
        <div>
            <div class="card card-body">
                <form method="get" action="{% url 'invoice:createInvoice' %}" id="filter-form">
                    {{ clientFilter.form }}
                    <button class="btn btn-primary" type="submit">Search</button>
                    <a class="btn btn-warning" href="{% url 'invoice:createInvoice' %}">Reset</a>
                </form>
            </div>
        </div>

        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Client Name</th>
                    <th>Actions</th>
                </tr>
                {% for i in clients %}
                <tr>
                    <form method="post" action="{% url 'invoice:createInvoice' %}">
                        {% csrf_token %}
                        <td>{{ i.name }}</td>
                        <td>
                            <input type="hidden" name="client" value="{{ i.id }}">
                            <button type="submit">Create Invoice</button>
                        </td>
                    </form>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-2"></div>
</div>


{% endblock content %}

invoice/templates/invoice/createProduct.html
{% extends "base/base.html" %}

{% block content %}
<div style="text-align: center;">
    <h1>Add Instrument</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ productForm }}
        <button type="submit">Save</button>
    </form>
    {% endblock content %}

</div>

invoice/templates/invoice/createProductType.html
{% extends "base/base.html" %}

{% block content %}
<div style="text-align: center;">
    <h1>Add Instrument Type</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ productTypeForm }}
        <button type="submit">Save</button>
    </form>
    {% endblock content %}
</div>

invoice/templates/invoice/editItemForm.html
{% extends "base/base.html" %}

{% block content %}

<h1>Edit Product</h1>

<form id="invoiceForm">
    {% csrf_token %}
    <label for="product">Select Product:</label>
    <select name="product" id="product">
        <option value="">Select a product</option>
        {% for product in products %}
            <option value="{{ product.id }}">{{ product.name }}</option>
        {% endfor %}
    </select>
    <label for="quantity">Quantity:</label>
    <input type="number" id="quantity" name="quantity" required min="1"><br>
    <p>site url {{site_url}}</p>
    
    <button type="submit">Submit Item</button>

</form>

<script>
    let site_url = '{{ site_url }}';
    let invoice = "{{ invoice_id }}";
    let id = `{{ itemId.id }}`;
    console.log(site_url)
    // Function to extract the CSRF token from a cookie
    function getCSRFToken() {
        const cookieValue = document.cookie
            .split('; ')
            .find(row => row.startsWith('csrftoken='))
            .split('=')[1];
        return cookieValue;
    }

    function putInvoiceData(invoice, product, quantity) {
        const apiUrl = site_url + '/editInvoiceItemAPI/'+ invoice + '/' + id + '/';  // Use the correct API URL
        const postData = {
            invoice: invoice,
            product: product,
            quantity: quantity,
        };

        return fetch(apiUrl, {
            method: 'PUT',  // Use PUT method for RESTful API
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCSRFToken(),
            },
            body: JSON.stringify(postData),
        })
        .then(response => {
            if (response.ok) {
                return response.json();
            } else {
                throw new Error('PUT request failed');
            }
        });
    }

    const invoiceForm = document.getElementById('invoiceForm');
    invoiceForm.addEventListener('submit',  e => {
        e.preventDefault();  // Prevent the default form submission
        const product = document.getElementById('product').value;
        const quantity = document.getElementById('quantity').value;
        putInvoiceData(invoice, product, quantity)
            .then(data => {
                // Handle the response data as needed

                // Redirect to the specified URL
                window.location.href = site_url + '/addItems/'+ invoice + '/';
            })
            .catch(error => {
                // Handle any errors
                console.error(error);
            });
    });
</script>

{% endblock content %}

invoice/templates/invoice/invoiceHistory.html
{% extends "base/base.html" %}

{% block content %}
<div class="row">
    <h1>Past Invoices</h1>
</div>

<div class="row">
    <table class="table">
        <thead>
          <tr>
            <th>Invoice Number</th>
            <th>Client</th>
            <th>Issue Date</th>
            <th>Status</th>
            <th>Actions</th> 
             
          </tr>
        </thead>
        <tbody>
          {% for invoice in invoices %}
            <tr>
              <td>{{ invoice.invoice_num }}</td>
              <td>{{ invoice.client }}</td>
              <td>{{ invoice.invoice_date }}</td>
              <td>{{ invoice.status }}</td>
              <td>
                <!-- Add a link or button to open the editInvoice view with a confirmation pop-up -->
                <a href="{% url 'invoice:addItems' invoice.invoice_num %}" onclick="return confirm('Are you sure you want to edit?')">Edit</a>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="4">No invoices available.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="pagination">
        <span class="step-links">
          {% if invoices.has_next %}
            <a href="?page={{ invoices.paginator.num_pages }}">last</a>
            <a href="?page={{ invoices.next_page_number }}">next</a>
          {% endif %}
        
          <span class="current-page">
            Page {{ invoices.number }} of {{ invoices.paginator.num_pages }}.
          </span>
        
          {% if invoices.has_previous %}
            <a href="?page={{ invoices.previous_page_number }}">previous</a>
            <a href="?page=1">first</a>
          {% endif %}
        </span>
      </div>

</div>

{% endblock %}