invoice/urls.py
from django.urls import path, re_path
from . import views
from trackingCard import views as trackingCardViews
from django.conf import settings
from django.conf.urls.static import static


app_name = 'invoice'

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    #path('home/', views.home, name='home'),
    path('home/', trackingCardViews.createWorkOrder, name='home'),
    path('createInvoice/', views.createInvoice, name='createInvoice'),
    path('createInvoice2/', views.createInvoice2, name='createInvoice2'),
    path("invoiceHistory/", views.invoiceHistory, name="invoiceHistory"),
    path("addProductsClients/", views.addProductsClients, name="addProductsClients"),
    path('addItems/<int:invoice_id>/', views.addItems, name='addItems'),
    path('editInvoiceItem/<int:invoice_pk>/<int:id>/', views.editInvoiceItem, name="editInvoiceItem"),
    path("pdf/<int:invoice_id>", views.pdf, name="pdf"),
    path("createClient/", views.createClient, name="createClient"),
    path("createClientContact/", views.createClientContact, name="createClientContact"),
    path('products/createProduct/', views.createProduct, name="createProduct"),
    path('products/createProductType/', views.createProductType, name="createProductType"),
    
    
    #path('register/', views.registerPage, name="registerPage"),
    path('login/', views.loginPage, name="loginPage"),
    path('logout/', views.logoutUser, name="logout"),
    path('check-login/', views.check_login, name='check_login'),
    
    
    path('trackingCardsPDF/<int:workOrder_id>', trackingCardViews.pdfTracker, name='pdfTracker'),
    path('customerTrackingPDF/<int:workOrder_id>', trackingCardViews.pdfCustomerTracking, name='pdfCustomerTracking'),
    path('shopWorkDashboard/', trackingCardViews.shopWorkDashboard, name='shopWorkDashboard'),
    path('createWorkOrder/', trackingCardViews.createWorkOrder, name='createWorkOrder'),
    path('addItemsWorkOrder/<int:workOrder_id>/', trackingCardViews.addItemsWorkOrder, name='addItemsWorkOrder'),
    path('customWorkOrderItem/<int:workOrder_id>/', trackingCardViews.customWorkOrderItem, name="customWorkOrderItem"),
    path('editWorkOrderItem/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItem, name="editWorkOrderItem"),
    path("workOrderHistory/", trackingCardViews.workOrderHistory, name="workOrderHistory"),
    path("deleteWorkOrderItem/<int:workOrder_id>/<int:id>/", trackingCardViews.deleteWorkOrderItem, name="deleteWorkOrderItem"),
    path("workOrderView/<int:workOrder>/", trackingCardViews.workOrderView, name="workOrderView"),
    path('signature_page/<int:workOrder_id>/', trackingCardViews.signature_page, name='signature_page'),
    path('signature_page/shopWorkDashboard', trackingCardViews.shopWorkDashboard, name='shopWorkDashboard'),



    path('invoice/api/createInvoice/', views.createInvoiceAPI, name='createInvoiceAPI'),
    path('invoice/api/invoiceAll/', views.invoiceAllAPI, name="invoiceAllAPI"),
    path('invoice/api/itemInvoice/<int:invoice_pk>/', views.itemInvoiceAPI, name="itemInvoiceAPI"),
    path('invoice/api/productsID/<int:id>/', views.productsIDAPI, name="productsIDAPI"),
    path('invoice/api/clientAll/', views.clientsAllAPI, name="clientAllAPI"),
    path('invoice/api/newestProduct/<int:invoice_pk>/', views.newestProductAPI, name="newestProductAPI"),
    path('invoice/api/editInvoiceItem/<int:invoice_pk>/<int:id>/', views.editInvoiceItemAPI, name="editInvoiceItemAPI"),
    path('invoice/api/deleteInvoiceItem/<int:id>/', views.deleteInvoiceItemAPI, name="deleteInvoiceItemAPI"),
    path('invoice/get_invoice_item_count/<int:invoice_id>/', views.get_invoice_item_count, name='get_invoice_item_count'),
    path('invoice/api/invoiceItemNumber/<int:id>/', views.itemInvoiceNumberAPI, name='invoiceItemNumberAPI'),

    path('workOrder/api/createWorkOrder/', trackingCardViews.createWorkOrderAPI, name='createWorkOrderAPI'),
    path('workOrder/api/itemWorkOrder/<int:workOrder_id>/', trackingCardViews.itemWorkOrderAPI, name="itemWorkOrderAPI"),
    path('workOrder/getWorkOrderItemCount/<int:workOrder_id>/', trackingCardViews.getWorkOrderItemCount, name='getWorkOrderItemCount'),
    path('workOrder/api/workOrderItemNumber/<int:id>/', trackingCardViews.itemWorkOrderNumberAPI, name='itemworkOrderNumberAPI'),
    path('workOrder/api/itemWorkOrder/<int:workOrder_id>/', trackingCardViews.itemWorkOrderAPI, name="itemWorkOrderAPI"),
    path('editWorkOrderItemAPI/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItemAPI, name="editWorkOrderItemAPI"),
    path('workOrder/api/deleteWorkOrderItem/', trackingCardViews.deleteWorkOrderItemAPI, name="deleteWorkOrderItemAPI"),
    path('workOrder/api/newestProduct/<int:workOrder_id>/', trackingCardViews.newestWorkOrderProductAPI, name="newestWorkOrderProductAPI"),
    path('workOrder/api/workOrderItemOther/<int:id>/', trackingCardViews.workOrderItemOther, name="workOrderItemOther"),
    path('workOrder/api/editWorkOrderItem/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItemAPI, name="editWorkOrderItemAPI"),
    path('workOrder/api/addColor/<int:workOrder_id>/', trackingCardViews.workOrderColorAPI, name="workOrderColorAPI"),
    path('workOrder/api/workOrderView/', trackingCardViews.workOrderViewAPI, name="workOrderViewAPI"),
    path('workOrder/api/workOrderEnrichment/', trackingCardViews.workOrderEnrichment, name="workOrderEnrichment"),
    path('workOrder/api/signature/', trackingCardViews.signatureAPI, name="signatureAPI"),
    path('workOrder/api/addItemTestAPI/', trackingCardViews.addItemTestAPI, name="addItemTestAPI"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoiceme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoice.urls")),
]

invoice/views.py
from django.shortcuts import render, redirect
from .models import *
from .filters import *
from .forms import *
from .serializers import *
from .urls import *
import requests
import json
from django.http import HttpResponse, JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from django.core.paginator import Paginator, Page
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import *
from datetime import date
import io
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter


'''
@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            
            return redirect('invoice:loginPage')

    context = {'form': form}

    return render(request, 'accounts/register.html', context)
'''
@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('invoice:home')
        else:
            messages.info(request, 'Username Or Password is incorrect')
    
    context = {}

    return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('invoice:loginPage')


def landingPage(request):
    context= {}
    return render(request, 'index/landing.html', context)



def check_login(request):
    if request.user.is_authenticated:
        return redirect('invoice:home')
    else:
        # Handle the case where the user is not authenticated.
        return redirect('invoice:loginPage')


@login_required(login_url='invoice:loginPage')
def home(request):
    context= {}
    return render(request, 'tracking/home.html', context)

@api_view(['POST'])
def createInvoiceAPI(request):
    if request.method == 'POST':
        serializer = invoiceSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET'])
def invoiceAllAPI(request):
    #http://127.0.0.1:8000/invoice/api/invoiceAll/
    if request.method == "GET":
        invoice = Invoice.objects.all()
        serializer = invoiceSerializer(invoice,many=True)
        return JsonResponse(serializer.data, safe=False)

@api_view(['GET'])
def clientsAllAPI(request):
    #http://127.0.0.1:8000/invoice/api/clientAll/
    if request.method == "GET":
        client = Client.objects.all()
        serializer = clientSerializer(client,many=True)
        return JsonResponse(serializer.data, safe=False)
    
@api_view(['PUT'])
def itemInvoiceNumberAPI(request, id):
    try:
        item = InvoiceItem.objects.get(pk=id)  # Use get() to retrieve a single instance
    except InvoiceItem.DoesNotExist:
        return JsonResponse({'error': 'Item not found'}, status=404)
    
    if request.method == "PUT":
        serializer = invoiceItemNumberSerializer(item, data=request.data)  # Pass request data to the serializer
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
    
    return JsonResponse({'error': 'Invalid request method'}, status=400)


@api_view(['GET','POST'])  
def itemInvoiceAPI(request, invoice_pk):
    if request.method == "GET":
        try:
            items = InvoiceItem.objects.filter(invoice=invoice_pk)
            serializer = invoiceItemSerializer(items, many=True)
            return Response(serializer.data)
        except InvoiceItem.DoesNotExist:
            return Response([], status=status.HTTP_200_OK)  # Return an empty list if no items are found for the given invoice
    elif request.method == "POST":
        serializer = invoiceItemSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

    # Handle other HTTP methods
    return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)


@api_view(['GET'])
def productsIDAPI(request, id):
    if request.method == "GET":
        product= Product.objects.get(pk=id)
        serializer = productSerializer(product)
        return JsonResponse(serializer.data, safe=False)
    return

@api_view(['GET'])
def newestProductAPI(request, invoice_pk):
    if request.method == "GET":
        try:
            # Get the specific invoice
            invoice = Invoice.objects.get(invoice_num=invoice_pk)

            # Get the most recent item for the given invoice
            item = InvoiceItem.objects.filter(invoice=invoice).order_by('-created_at')[:1]

            serializer = invoiceItemSerializer(item, many=True)
            return JsonResponse(serializer.data, safe=False)
        except Invoice.DoesNotExist:
            # Handle the case where the specified invoice does not exist
            return JsonResponse({'error': 'Invoice not found'}, status=404)
        
@api_view(['PUT'])
def editInvoiceItemAPI(request, invoice_pk, id):
    try:
        # Try to get the InvoiceItem with the specified ID
        invoice_item = InvoiceItem.objects.get(pk=id)
    except InvoiceItem.DoesNotExist:
        # If the InvoiceItem does not exist, return a 404 Not Found response
        return Response({'detail': 'InvoiceItem not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        # Assuming you have a serializer for your InvoiceItem model
        serializer = invoiceItemSerializer(invoice_item, data=request.data)
        
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    return Response({'detail': 'Invalid request method'}, status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['DELETE'])
def deleteInvoiceItemAPI(request, id):
    try:
        # Try to get the InvoiceItem with the specified ID
        invoice_item = InvoiceItem.objects.get(pk=id)
    except InvoiceItem.DoesNotExist:
        # If the InvoiceItem does not exist, return a 404 Not Found response
        return Response({'detail': 'InvoiceItem not found'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == "DELETE":
        # If the request method is DELETE, delete the InvoiceItem
        invoice_item.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
@api_view(['GET']) 
def get_invoice_item_count(request, invoice_id):
    count = InvoiceItem.objects.filter(invoice_id=invoice_id).count()
    data = {'count': count}
    return JsonResponse(data)


# this is probably how i should do it
@login_required(login_url='invoice:loginPage')
def createInvoice2(request):
    clients2 = Client.objects.all()
    clientFilter2 = ClientFilter(request.GET, queryset=clients2)
    clients2 = clientFilter2.qs

    form2 = InvoiceForm2(request.POST) 

    if request.method == 'POST':
        
        if form2.is_valid():
            # Save the form to create an invoice
            invoice=form2.save()
            # Redirect to the next step (e.g., 'addItems') with the invoice ID
            return redirect('invoice:addItems', invoice_id=invoice.id)

    context = {
        'form2': form2,
        'clients': clients2,
        'clientFilter': clientFilter2
    }

    return render(request, 'invoice/createInvoice.html', context)


@login_required(login_url='invoice:loginPage')
def createInvoice(request):
    clients = Client.objects.all()
    clientFilter = ClientFilter(request.GET, queryset=clients)
    clients = clientFilter.qs
    if request.method == 'POST':
        form = InvoiceForm(request.POST)
        if form.is_valid():
            client_id = form.cleaned_data['client'].id 

            today = date.today()

            # Format the date as a string in 'YYYY-MM-DD' format
            invoice_date_str = today.strftime('%Y-%m-%d')


            # Create the API payload using the serialized client data
            api_payload = {
                "client": client_id,
                "invoice_date": invoice_date_str,
                "items": [],
                "status": "Draft"
            }

            # Define the API endpoint URL where you want to send the POST request
            api_url = f'{settings.SITE_URL}/invoice/api/createInvoice/'
            print(api_url)
            print("test")
            print(api_payload)

            try:
                response = requests.post(api_url, json=api_payload)


                if response.status_code == 201:  # Replace with the appropriate status code
                    response_data = json.loads(response.text)
                    invoice_id = response_data.get('invoice_num')
                    print(response_data)
                    print(invoice_id)
                    # Invoice created successfully
                    return redirect('invoice:addItems', invoice_id)
                else:
                    # Handle API call errors, e.g., show an error message
                    return render(request, 'invoice/createInvoice.html', {'form': form, 'error_message': 'Failed to create invoice'})

            except requests.exceptions.RequestException as e:

invoice/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!DOCTYPE html>
<html>
    <head>
        <title>InvoiceMe</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    </head>

    <style>
       .dropdown-toggle::after {
            display: none;
        }
        .custom-link {
            color: black; /* Change this to the desired text color */
            text-decoration: none; /* Optional: Remove underline */
        }

        .custom-link:hover {
            color: #555; /* Change this to the desired text color on hover */
        }
    </style>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{% static 'img/simnarLogo.png' %}" alt="Simnar Surgical" style="height: 50px;">
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse text-dark navbar-brand" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-plus-square"></i> Instruments/Clients
                </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'invoice:createClient' %}">Add Account</a></li>
                        <li><a class="dropdown-item" href="{% url 'invoice:createClientContact' %}">Add Account Contact</a></li>
                        <li><a class="dropdown-item" href="{% url 'invoice:createProduct' %}">Add Instrument</a></li>
                        <li><a class="dropdown-item" href="{% url 'invoice:createProductType' %}">Add Instrument Type</a></li>
                        <!--<li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>-->
                    </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'invoice:createWorkOrder' %}">Create Take Back Sheet</a>
              </li>
              <li class="nav-item">
                <li><a class="nav-link" href="{% url 'invoice:workOrderHistory' %}"><i class="bi bi-file-text"></i> History</a></li>
              </li>
              <li class="nav-item">
                <li><a class="nav-link" href="{% url 'invoice:shopWorkDashboard' %}"><i class="bi bi-clipboard2-data-fill"></i>Dashboard</a></li>
              </li>
            </ul>
            <div class="d-flex">
                {% if user.is_authenticated %}
                    <ul class="nav-item dropdown">
                        <a class="nav-link custom-link" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-file-person-fill"></i> {{ user.username }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item custom-link" href="#"><i class="bi bi-pencil-square"></i> Edit Profile</a></li>
                            <li><a class="dropdown-item custom-link" href="#"><i class="bi bi-mailbox-flag"></i> Report an Error</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item custom-link" href="{% url 'invoice:logout' %}"><i class="bi bi-box-arrow-right"></i> Logout</a></li>
                        </ul>
                    </ul>
                {% else %}
                    <a href="{% url 'invoice:loginPage' %}" class="nav-item nav-link custom-link">Login</a>
                {% endif %}
            </div>   
          </div>
        </div>
      </nav>
    <!--
    <nav class="navbar">
        <div class="container-xxl">
            <a href="#" class="navbar-brand">
                <span class="fw-bold text-secondary">
                    Invoiceme
                </span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>

            </button>
            <div class="collapse navbar-collapser" id="main-nav">
                <ul class="navbar-nav"> I need to re add the links to create all of the invoice stuff
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:addProductsClients' %}">Add Products/Clients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:addProductsClients' %}">Add Products/Clients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:addProductsClients' %}">Add Products/Clients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:addProductsClients' %}">Add Products/Clients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:addProductsClients' %}">Add Products/Clients</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:createWorkOrder' %}">Create Take Back Sheet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:workOrderHistory' %}">Take Back Sheet History</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invoice:shopWorkDashboard' %}">Shop Work Dashboard</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    -->
    <div class="container-fluid">
        {% block content %}{% endblock content %}

    </div>
    <div class="container-fluid" style="flex-grow: 1; min-width: 0;"></div>
    </div>
<!--<footer class="row">
    <div class="col-md-4"></div>
        <div class="col-md-4 sticky-bottom" style="text-align: center;">
          Copyright &copy; Jordan Greer
        </div>
    <div class="col-md-4"></div>
</footer>-->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>