invoice/urls.py
from django.urls import path, re_path
from . import views
from trackingCard import views as trackingCardViews
from django.conf import settings
from django.conf.urls.static import static


app_name = 'invoice'

urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    #path('home/', views.home, name='home'),
    path('home/', trackingCardViews.createWorkOrder, name='home'),
    path('createInvoice/', views.createInvoice, name='createInvoice'),
    path('createInvoice2/', views.createInvoice2, name='createInvoice2'),
    path("invoiceHistory/", views.invoiceHistory, name="invoiceHistory"),
    path("addProductsClients/", views.addProductsClients, name="addProductsClients"),
    path('addItems/<int:invoice_id>/', views.addItems, name='addItems'),
    path('editInvoiceItem/<int:invoice_pk>/<int:id>/', views.editInvoiceItem, name="editInvoiceItem"),
    path("pdf/<int:invoice_id>", views.pdf, name="pdf"),
    path("createClient/", views.createClient, name="createClient"),
    path("createClientContact/", views.createClientContact, name="createClientContact"),
    path('products/createProduct/', views.createProduct, name="createProduct"),
    path('products/createProductType/', views.createProductType, name="createProductType"),
    
    
    #path('register/', views.registerPage, name="registerPage"),
    path('login/', views.loginPage, name="loginPage"),
    path('logout/', views.logoutUser, name="logout"),
    path('check-login/', views.check_login, name='check_login'),
    
    
    path('trackingCardsPDF/<int:workOrder_id>', trackingCardViews.pdfTracker, name='pdfTracker'),
    path('customerTrackingPDF/<int:workOrder_id>', trackingCardViews.pdfCustomerTracking, name='pdfCustomerTracking'),
    path('shopWorkDashboard/', trackingCardViews.shopWorkDashboard, name='shopWorkDashboard'),
    path('createWorkOrder/', trackingCardViews.createWorkOrder, name='createWorkOrder'),
    path('addItemsWorkOrder/<int:workOrder_id>/', trackingCardViews.addItemsWorkOrder, name='addItemsWorkOrder'),
    path('customWorkOrderItem/<int:workOrder_id>/', trackingCardViews.customWorkOrderItem, name="customWorkOrderItem"),
    path('editWorkOrderItem/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItem, name="editWorkOrderItem"),
    path("workOrderHistory/", trackingCardViews.workOrderHistory, name="workOrderHistory"),
    path("deleteWorkOrderItem/<int:workOrder_id>/<int:id>/", trackingCardViews.deleteWorkOrderItem, name="deleteWorkOrderItem"),
    path("workOrderView/<int:workOrder>/", trackingCardViews.workOrderView, name="workOrderView"),
    path('signature_page/<int:workOrder_id>/', trackingCardViews.signature_page, name='signature_page'),
    path('signature_page/shopWorkDashboard', trackingCardViews.shopWorkDashboard, name='shopWorkDashboard'),



    path('invoice/api/createInvoice/', views.createInvoiceAPI, name='createInvoiceAPI'),
    path('invoice/api/invoiceAll/', views.invoiceAllAPI, name="invoiceAllAPI"),
    path('invoice/api/itemInvoice/<int:invoice_pk>/', views.itemInvoiceAPI, name="itemInvoiceAPI"),
    path('invoice/api/productsID/<int:id>/', views.productsIDAPI, name="productsIDAPI"),
    path('invoice/api/clientAll/', views.clientsAllAPI, name="clientAllAPI"),
    path('invoice/api/newestProduct/<int:invoice_pk>/', views.newestProductAPI, name="newestProductAPI"),
    path('invoice/api/editInvoiceItem/<int:invoice_pk>/<int:id>/', views.editInvoiceItemAPI, name="editInvoiceItemAPI"),
    path('invoice/api/deleteInvoiceItem/<int:id>/', views.deleteInvoiceItemAPI, name="deleteInvoiceItemAPI"),
    path('invoice/get_invoice_item_count/<int:invoice_id>/', views.get_invoice_item_count, name='get_invoice_item_count'),
    path('invoice/api/invoiceItemNumber/<int:id>/', views.itemInvoiceNumberAPI, name='invoiceItemNumberAPI'),

    path('workOrder/api/createWorkOrder/', trackingCardViews.createWorkOrderAPI, name='createWorkOrderAPI'),
    path('workOrder/api/itemWorkOrder/<int:workOrder_id>/', trackingCardViews.itemWorkOrderAPI, name="itemWorkOrderAPI"),
    path('workOrder/getWorkOrderItemCount/<int:workOrder_id>/', trackingCardViews.getWorkOrderItemCount, name='getWorkOrderItemCount'),
    path('workOrder/api/workOrderItemNumber/<int:id>/', trackingCardViews.itemWorkOrderNumberAPI, name='itemworkOrderNumberAPI'),
    path('workOrder/api/itemWorkOrder/<int:workOrder_id>/', trackingCardViews.itemWorkOrderAPI, name="itemWorkOrderAPI"),
    path('editWorkOrderItemAPI/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItemAPI, name="editWorkOrderItemAPI"),
    path('workOrder/api/deleteWorkOrderItem/', trackingCardViews.deleteWorkOrderItemAPI, name="deleteWorkOrderItemAPI"),
    path('workOrder/api/newestProduct/<int:workOrder_id>/', trackingCardViews.newestWorkOrderProductAPI, name="newestWorkOrderProductAPI"),
    path('workOrder/api/workOrderItemOther/<int:id>/', trackingCardViews.workOrderItemOther, name="workOrderItemOther"),
    path('workOrder/api/editWorkOrderItem/<int:workOrder_id>/<int:id>/', trackingCardViews.editWorkOrderItemAPI, name="editWorkOrderItemAPI"),
    path('workOrder/api/addColor/<int:workOrder_id>/', trackingCardViews.workOrderColorAPI, name="workOrderColorAPI"),
    path('workOrder/api/workOrderView/', trackingCardViews.workOrderViewAPI, name="workOrderViewAPI"),
    path('workOrder/api/workOrderEnrichment/', trackingCardViews.workOrderEnrichment, name="workOrderEnrichment"),
    path('workOrder/api/signature/', trackingCardViews.signatureAPI, name="signatureAPI"),
    path('workOrder/api/addItemTestAPI/', trackingCardViews.addItemTestAPI, name="addItemTestAPI"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoiceme/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoice.urls")),
]

trackingCard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'trackingCard'

urlpatterns = [


]

invoice/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.TextField()
    tax = models.FloatField(max_length=10, default= 0.0)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    #street_address = models.CharField(max_length=255)
    #city = models.CharField(max_length=100)
    #state = models.CharField(max_length=50)
    #postal_code = models.CharField(max_length=20)
    tax = models.FloatField(default=0.0)

    def __str__(self):
        return self.name
    
class ClientContact(models.Model):
    STATUS_CHOICES = [
        ('Primary', 'primary'),
        ('WorkOrder', 'WorkOrder'),
        ('Normal', 'Normal')
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True)  # Changed to CharField
    email = models.EmailField()
    client = models.ForeignKey(Client, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Normal')
    created_by = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Color(models.Model):
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.color

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True) # i need to get rid of this?

    def __str__(self):
        return self.name
    

    
class Discount(models.Model):
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount)
    
class Tax(models.Model):
    amount = models.FloatField()
    description = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount)
    

class Invoice(models.Model):
    STATUS_CHOICES = [
        ('Draft', 'Draft'),
        ('Sent', 'Sent'),
        ('Paid', 'Paid'),
        ('Overdue', 'Overdue'),
    ]

    # Auto-incrementing primary key
    invoice_num = models.AutoField(primary_key=True)

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    invoice_date = models.DateField()
    items = models.ManyToManyField(Product, through='InvoiceItem', blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Draft')
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.invoice_num)

class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    number = models.CharField(max_length=10, default="")
    created_by = models.CharField(max_length=100, blank=True, null=True)


class WorkOrders(models.Model):
    STATUS_CHOICES = [
        ('Waiting_on_Assignment', 'Waiting on Assignment'),
        ('Being_Worked_On', 'Being Worked On'),
        ('Ready', 'Ready'),
        ('Delivered', 'Delivered'),
        ('Rush', 'Rush'),
    ]

    # Auto-incrementing primary key
    workOrder_num = models.AutoField(primary_key=True)

    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    workOrder_date = models.DateField()
    items = models.ManyToManyField(Product, through='WorkorderItem', blank=True)
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default="Waiting_on_Assignment")
    created_at = models.DateTimeField(auto_now_add=True)
    is_rush = models.BooleanField(default=False)
    return_by = models.DateField(null=True, default=None)
    quote_required = models.BooleanField(default=False)
    specialInstructions = models.CharField(max_length=250, default="", null=True, blank=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    color = models.CharField(max_length=100, blank=True, null=True)
    account_contact = models.ForeignKey(ClientContact, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return str(self.workOrder_num)
    

class WorkOrderItem(models.Model):
    STATUS_CHOICES = [
        ('Waiting_on_Assignment', 'Waiting on Assignment'),
        ('Checked_Out', 'Checked Out'),
        ('Needs_QC', 'Needs QC'),
        ('Parts_On_Order', 'Parts On Order'),
        ('QC_PASS', 'QC PASS'),
        ('QC_FAIL', 'QC FAIL'),
    ]

    QC_STATUS_CHOICES = [
        ('QC_FAIL', 'QC FAIL'),
        ('QC_PASS', 'QC PASS'),
        ('WAITING_QC', 'Waiting On QC'),
        ('NO_QC', '')
    ]



    workOrder = models.ForeignKey(WorkOrders, on_delete=models.CASCADE)
    
    # Set product to allow blank and null values
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    last_updated_at = models.DateTimeField(auto_now=True)
    description = models.TextField(max_length=35, blank=True, null=True)
    issue = models.TextField(max_length=125, blank=True, null=True)
    mfgnum = models.CharField(max_length=50, blank=True, null=True)
    number = models.CharField(max_length=10, default="", blank=True, null=True)
    status = models.CharField(max_length=25, choices=STATUS_CHOICES, default="Waiting_on_Assignment")
    qc = models.CharField(max_length=20, choices=QC_STATUS_CHOICES, default="NO_QC")
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True)
    
    # Add fields for custom product
    custom_product_name = models.CharField(max_length=200, blank=True, null=True)
    custom_product_description = models.TextField(max_length=100, blank=True, null=True)
    custom_product_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    technician = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def save(self, *args, **kwargs):
        self.last_updated_at = timezone.now()
        super(WorkOrderItem, self).save(*args, **kwargs)

class Signature(models.Model):
    image = models.ImageField(upload_to='static/img/signatures/') # make non editable
    customer_last_name = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    workOrder = models.ForeignKey(WorkOrders, on_delete=models.CASCADE) # remove default

    def __str__(self):
        return f'Signature {self.id}'
    
class CompanyRepSignature(models.Model):
    companyRep = models.ImageField(upload_to='static/img/signatures/') # make non editable
    last_name = models.CharField(max_length=50, blank=True, null=True)
    workOrder = models.ForeignKey(WorkOrders, on_delete=models.CASCADE) # remove default
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Signature {self.id}'
    

        

trackingCard/models.py
from django.db import models

# Create your models here.

trackingCard/templates/tracking/createWorkOrder.html
{% extends "base/base.html" %}

{% block content %}
<h1 style="text-align: center;">Create Take Back Sheet</h1>

<div class="row" style="text-align: center;">
    <div class="col-2"></div>
    <div class="col-md-8">
        <div>
            <div class="card card-body">
                <form method="get" action="{% url 'invoice:createWorkOrder' %}" id="filter-form">
                    {{ clientFilter.form }}
                    <button class="btn btn-secondary" type="submit">Search</button>
                    <a class="btn btn-warning" href="{% url 'invoice:createWorkOrder' %}">Reset</a>
                </form>
            </div>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Client Name</th>
                    <th>Actions</th>
                </tr>
                {% for i in clients %}
                <tr>
                    <form method="post" action="{% url 'invoice:createWorkOrder' %}">
                        {% csrf_token %}
                        <td>{{ i.name }}</td>
                        <td>
                            <input type="hidden" name="client" value="{{ i.id }}">
                            <button type="submit">Create Take Back Sheet</button>
                        </td>
                    </form>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-2"></div>
</div>


{% endblock content %}

trackingCard/templates/tracking/customWorkOrderItem.html
{% extends "base/base.html" %}

{% block content %}
<div class="row">
    <div class="col-5">

    </div>
    <div class="col-1">
        <div style="padding-top: 15px;">
            <form method="post">
                {% csrf_token %}
                {{ form.as_table }}
                <button type="submit" class="btn-primary">Submit</button>
            </form>
        </div>
    </div>
    <div class="col-2">

    </div>

</div>

{% endblock content %}

trackingCard/templates/tracking/draw_signature.html
{% extends "base/base.html" %}
{% load static %}



{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/signature_pad/1.5.3/signature_pad.min.js"></script>
<div style="text-align:  center;">
    <h1>Signature Page</h1>
    
    <iframe src="{% url 'invoice:pdfCustomerTracking' workOrder_id %}#toolbar=0" width="60%" height="600"></iframe>
    <p>Sign Here:</p>

    <canvas id="signature-pad" width="700" height="200" style="border: 2px solid black;"></canvas>
    <br>
    <div class="row">
        <div class="col">
            
        </div>
        <div class="col">
            <!--<p>Enter Last Name</p>
            <input type="text" name='customerLastName'>
            -->     
            <!-- Include the CSRF token inside a form element -->
            <form method="post" enctype="multipart/form-data" id="signature-form">
                {% csrf_token %}
                {{ form.as_p }}   
                <button type="submit">Upload Signature</button>
            </form>
        </div>
        <div class="col">
            <button id="clear-button">Clear Signature</button>
        </div>
        <div class="col">
            
        </div>
    </div>
    <div class="row" style="min-height: 150px;">

    </div>

</div>

    
    


<script>
        let workOrder_id = '{{workOrder_id}}';
        let site_url = '{{ site_url }}';
        console.log(workOrder_id);

        $(document).ready(function () {
        var signaturePad = new SignaturePad(document.getElementById('signature-pad'), {
            penColor: 'orange',
            backgroundColor: 'white',
            minWidth: 5,  // Adjust this value to make the signature thicker
            maxWidth: 7   // Adjust this value to control the maximum thickness
        });
        var clearButton = document.getElementById('clear-button');

        clearButton.addEventListener('click', function () {
            signaturePad.clear();
        });
    });

        


function dataURItoBlob(dataURI) {
    var byteString = atob(dataURI.split(',')[1]);
    var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
    var ab = new ArrayBuffer(byteString.length);
    var ia = new Uint8Array(ab);

    for (var i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }

    return new Blob([ab], { type: mimeString });
}
      $(document).ready(function () {
    var signaturePad = new SignaturePad(document.getElementById('signature-pad'));
    var clearButton = document.getElementById('clear-button');
    var form = document.getElementById('signature-form');

    
    clearButton.addEventListener('click', function () {
        signaturePad.clear();
    });

    form.addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent the default form submission

        // Create a FormData object to send the form data
        var formData = new FormData(form);

        // Convert the signature data to an image and append it to the FormData
        var signatureData = signaturePad.toDataURL();
        var blob = dataURItoBlob(signatureData);
        formData.append('image', blob, 'signature.png');
        formData.append('workOrder_id', workOrder_id);

        // Use jQuery to submit the FormData via AJAX
        $.ajax({
            type: 'POST',
            url: site_url + '/workOrder/api/signature/', // Replace with your actual endpoint
            data: formData,
            processData: false,
            contentType: false,
            success: function (response) {
                signaturePad.clear();
                window.location.href = "{% url 'invoice:createWorkOrder' %}";
            }
        });
    });
});
</script>
 
    
</body>
</html>




{% endblock %}

trackingCard/templates/tracking/editWorkOrderItemForm.html
{% extends "base/base.html" %}

{% block content %}

<h1>Edit nstrument</h1>

<form id="workOrderForm">
    {% csrf_token %}
    <label for="product">Select Instrument:</label>
    <select name="product" id="product">
        <option value="">Select an Instrument</option>
        {% for product in products %}
            <option value="{{ product.id }}">{{ product.name }}</option>
        {% endfor %}
    </select>
    <label for="quantity">Quantity:</label>
    <input type="number" id="quantity" name="quantity" required min="1"><br>
    
    <button type="submit">Submit Change</button>

</form>

<script>
    let site_url = '{{ site_url }}';
    let invoice = "{{ invoice_id }}";
    let id = `{{ itemId.id }}`;
    console.log(site_url)
    // Function to extract the CSRF token from a cookie
    function getCSRFToken() {
        const cookieValue = document.cookie
            .split('; ')
            .find(row => row.startsWith('csrftoken='))
            .split('=')[1];
        return cookieValue;
    }

    function putInvoiceData(invoice, product, quantity) {
        const apiUrl = site_url + '/invoice/api/editWorkOrderItem/'+ invoice + '/' + id + '/';  // Use the correct API URL
        const postData = {
            invoice: invoice,
            product: product,
            quantity: quantity,
        };

        return fetch(apiUrl, {
            method: 'PUT',  // Use PUT method for RESTful API
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCSRFToken(),
            },
            body: JSON.stringify(postData),
        })
        .then(response => {
            if (response.ok) {
                return response.json();
            } else {
                throw new Error('PUT request failed');
            }
        });
    }

    const invoiceForm = document.getElementById('workOrderForm');
    invoiceForm.addEventListener('submit',  e => {
        e.preventDefault();  // Prevent the default form submission
        const product = document.getElementById('product').value;
        const quantity = document.getElementById('quantity').value;
        putInvoiceData(invoice, product, quantity)
            .then(data => {
                // Handle the response data as needed

                // Redirect to the specified URL
                window.location.href = site_url + '/addItems/'+ workOrder_id + '/';
            })
            .catch(error => {
                // Handle any errors
                console.error(error);
            });
    });
</script>

{% endblock content %}

trackingCard/templates/tracking/shopWorkDashboard.html
{% extends "base/base.html" %}

{% block content %}

<h1 style="text-align: center;">Shop Work Dashboard</h1>

<div class="row" style="text-align: center;">
    <div class="col-2 card card-body" style="margin: 15px;">
        <div>Rush Take Backs</div>
        <table>
            <thead>
                <tr>
                    <th>Account</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for r in rush_workOrders %}
                    <tr>
                        <td><a href="{% url 'invoice:workOrderView' r.workOrder_num %}">{{ r.client }}</a></td>
                        <td>{{ r.return_by }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-2 card card-body" style="margin: 15px;">
        <div>Take Backs Due Next</div>
        <table>
            <thead>
                <tr>
                    <th>Due Date</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for workOrder in latest_workOrders %}
                    <tr>
                        <td>{{ workOrder.return_by }}</td>
                        
                        <td><a href="{% url 'invoice:workOrderView' workOrder.workOrder_num %}">{{ workOrder.client }} </a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-2 card card-body" style="margin: 15px;">
        <div>Instruments Waiting on Parts</div>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for i in instruments_waiting_on_parts %}
                    <tr>
                        <td>
                            {% if i.product.id == 2 %}
                                <a href="{% url 'invoice:workOrderView' i.workOrder %}">{{ i.custom_product_name }}</a>
                            {% else %}
                                <a href="{% url 'invoice:workOrderView' i.workOrder %}">{{ i.product.name }}</a>
                            {% endif %}
                        </td>
                        <td>{{ i.workOrder.client }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock content %}

trackingCard/templates/tracking/workOrderHistory.html
{% extends "base/base.html" %}

{% block content %}
<div class="row">
    <h1 style="text-align: center;">History of Take Back Sheets</h1>
</div>
<div class="row" style="text-align: center;">
    <table class="table">
        <thead>
          <tr>
            <th>Take Back Sheet Number</th>
            <th>Client</th>
            <th>Issue Date</th>
            <th>Color</th>
            <th>Status</th>
            <th>View</th>
            <th>Actions</th>          
          </tr>
        </thead>
        <tbody>       
          {% for workOrder in workOrders %}
            <tr>
              <td>{{ workOrder.workOrder_num }}</td>
              <td>{{ workOrder.client }}</td>
              <td>{{ workOrder.workOrder_date }}</td>
              <td>
                {{ workOrder.color }}
                <div style="width: 15px; height: 15px; display: inline-block; background-color: {{ workOrder.color }};"></div>              
              </td>
              <td>{{ workOrder.get_status_display }}</td>
              <td>
                <a href="{% url 'invoice:workOrderView' workOrder %}"><i class="bi bi-eye"></i></a>
              </td>
              <td>
                <a href="{% url 'invoice:addItemsWorkOrder' workOrder.workOrder_num %}" ><i class="bi bi-pencil-square"></i></a>
              </td>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="4">No Take Back Sheets available.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="pagination d-flex justify-content-center align-items-center center-content">
        <span class="step-links">
          {% if workOrders.has_next %}
            <a href="?page={{ workOrders.paginator.num_pages }}">last</a>
            <a href="?page={{ workOrders.next_page_number }}">next</a>
          {% endif %}       
          <span class="current-page">
            Page {{ workOrders.number }} of {{ workOrders.paginator.num_pages }}.
          </span>       
          {% if workOrders.has_previous %}
            <a href="?page={{ workOrders.previous_page_number }}">previous</a>
            <a href="?page=1">first</a>
          {% endif %}
        </span>
      </div>
</div>

{% endblock %}